// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYxuOkskYaApUlFe7-ZJSroMlYlc3lnuk',
    appId: '1:1004176701320:web:37d48275b7bbd57411ac3d',
    messagingSenderId: '1004176701320',
    projectId: 'smarttemp-59bba',
    authDomain: 'smarttemp-59bba.firebaseapp.com',
    databaseURL: 'https://smarttemp-59bba-default-rtdb.firebaseio.com',
    storageBucket: 'smarttemp-59bba.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4LWLPkZxvHFEcwjg3WQNrso8CFlNuuFU',
    appId: '1:1004176701320:android:f8b194499aa1b7fe11ac3d',
    messagingSenderId: '1004176701320',
    projectId: 'smarttemp-59bba',
    databaseURL: 'https://smarttemp-59bba-default-rtdb.firebaseio.com',
    storageBucket: 'smarttemp-59bba.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABN_mvsMctWpfihseFD9hsBFcIjubTQaM',
    appId: '1:1004176701320:ios:e86e08ea3135064511ac3d',
    messagingSenderId: '1004176701320',
    projectId: 'smarttemp-59bba',
    databaseURL: 'https://smarttemp-59bba-default-rtdb.firebaseio.com',
    storageBucket: 'smarttemp-59bba.firebasestorage.app',
    iosBundleId: 'com.example.smartTemp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABN_mvsMctWpfihseFD9hsBFcIjubTQaM',
    appId: '1:1004176701320:ios:e86e08ea3135064511ac3d',
    messagingSenderId: '1004176701320',
    projectId: 'smarttemp-59bba',
    databaseURL: 'https://smarttemp-59bba-default-rtdb.firebaseio.com',
    storageBucket: 'smarttemp-59bba.firebasestorage.app',
    iosBundleId: 'com.example.smartTemp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYxuOkskYaApUlFe7-ZJSroMlYlc3lnuk',
    appId: '1:1004176701320:web:209b6ffbf339561411ac3d',
    messagingSenderId: '1004176701320',
    projectId: 'smarttemp-59bba',
    authDomain: 'smarttemp-59bba.firebaseapp.com',
    databaseURL: 'https://smarttemp-59bba-default-rtdb.firebaseio.com',
    storageBucket: 'smarttemp-59bba.firebasestorage.app',
  );

}